In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [2]:
df= pd.read_csv("play.csv")
df

DAY   Outlook Temperature Humidity   Wind  PlayTennis
0    D1     Sunny         Hot     High    Weak         No
1    D2     Sunny         Hot     High  Strong         No
2    D3  Overcast         Hot     High    Weak        Yes
3    D4      Rain        Mild     High    Weak        Yes
4    D5      Rain        Cold   Normal    Weak        Yes
5    D6      Rain        Cold   Normal  Strong         No
6    D7  Overcast        Cold   Normal  Strong        Yes
7    D8     Sunny        Mild     High    Weak         No
8    D9     Sunny        Cold   Normal    Weak        Yes
9   D10      Rain        Mild   Normal    Weak        Yes
10  D11     Sunny        Mild   Normal  Strong        Yes
11  D12  Overcast        Mild     High  Strong        Yes
12  D13  Overcast         Hot   Normal    Weak        Yes
13  D14      Rain        Mild     High  Strong         No

In [5]:
arr = np.array([2,3,4,4,5])
value,counts = np.unique(arr)
value

ValueError: too many values to unpack (expected 2)

In [3]:
def entropy(target_col):
    elements,counts = np.unique(target_col,return_counts = True)
    print(elements)
    print(counts)
    entropy = np.sum([(-counts[i]/np.sum(counts))*np.log2(counts[i]/np.sum(counts)) for i in range(len(elements))])
    return entropy
#entropy(df.iloc[:,-1])



# # Formula for calculating Gain :

#  def InfoGain(data,split_attribute_name,target_name):
#     #Calculate the entropy of the total dataset
#     total_entropy = entropy(data[target_name])
    
#     ##Calculate the entropy of the dataset
#     #Calculate the values and the corresponding counts for the split attribute
#     vals,counts= np.unique(data[split_attribute_name],return_counts=True)
    
#     #Calculate the weighted entropy
#     Weighted_Entropy = np.sum([(counts[i]/np.sum(counts))*entropy(data.where(data[split_attribute_name]==vals[i]).dropna()[target_name]) for i in 
#     range(len(vals))])
    
#     #Calculate the information gain
#     Information_Gain = total_entropy - Weighted_Entropy
#     return Information_Gain
# InfoGain(df,"Humidity","PlayTennis")   

In [4]:
#INFORMATION GAIN

def entropy(target_col):
    elements,counts = np.unique(target_col,return_counts = True)
   #print(elements)
   #print(counts)
    arr_val = []
    for i in range(len(elements)):
        mult = counts[i]/np.sum(counts)
        log_val = np.log2(mult)
        arr_val.append(mult*log_val)
    return -1* np.sum(arr_val)
    entropy = np.sum([(-counts[i]/np.sum(counts))*np.log2(counts[i]/np.sum(counts)) for i in range(len(elements))])
    return entropy
entropy(df.iloc[:,-1])
#that is for entropy calculation



0.9402859586706311

In [5]:
def InfoGain(data,split_attribute_name,target_name):
   #Calculate the entropy of the total dataset
    total_entropy = entropy(data[target_name])
   
   ##Calculate the entropy of the dataset
   #Calculate the values and the corresponding counts for the split attribute
    vals,counts= np.unique(data[split_attribute_name],return_counts=True)
   
   #Calculate the weighted entropy
   
    sum_weights = []
    for i in range(len(vals)):
        mul = counts[i]/np.sum(counts)
        arr_val = data.where(data[split_attribute_name]==vals[i])[target_name]
        sum_weights.append(mul*entropy(arr_val))
       
    Weighted_Entropy = np.sum(sum_weights)
    #Calculate the information gain
    Information_Gain = total_entropy - Weighted_Entropy
    return Information_Gain
   
InfoGain(df,'Humidity','PlayTennis') 

TypeError: '<' not supported between instances of 'float' and 'str'

In [6]:
df= pd.read_csv("play.csv")
df

DAY   Outlook Temperature Humidity   Wind  PlayTennis
0    D1     Sunny         Hot     High    Weak         No
1    D2     Sunny         Hot     High  Strong         No
2    D3  Overcast         Hot     High    Weak        Yes
3    D4      Rain        Mild     High    Weak        Yes
4    D5      Rain        Cold   Normal    Weak        Yes
5    D6      Rain        Cold   Normal  Strong         No
6    D7  Overcast        Cold   Normal  Strong        Yes
7    D8     Sunny        Mild     High    Weak         No
8    D9     Sunny        Cold   Normal    Weak        Yes
9   D10      Rain        Mild   Normal    Weak        Yes
10  D11     Sunny        Mild   Normal  Strong        Yes
11  D12  Overcast        Mild     High  Strong        Yes
12  D13  Overcast         Hot   Normal    Weak        Yes
13  D14      Rain        Mild     High  Strong         No

In [46]:
x = df.iloc[:,1:5].values
y = df.iloc[:,-1].values


In [47]:
from sklearn.preprocessing import LabelEncoder
rc = LabelEncoder()
x[:,0]=rc.fit_transform(x[:,0])
y=rc.fit_transform(y)

In [48]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.5)


In [49]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
x_train = ss.fit_transform(x_train)
x_test = ss.transform(x_test)


C:\Users\User\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [50]:
from sklearn.decomposition import PCA as p
ppp = p(n_components=2)
x_train = ppp.fit_transform(x_train)
x_test = ppp.transform(x_test)


In [51]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 2)
knn.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=2, p=2,
           weights='uniform')

In [52]:
pred = knn.predict(x_test)
pred

array([0, 1, 0, 0, 0, 1, 0], dtype=int64)

In [53]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,pred)

In [54]:
cm

array([[2, 0],
       [3, 2]], dtype=int64)

In [55]:
tp = cm[0,0]

In [56]:
fn = cm[0,1]
fp=cm[1,0]
tn=cm[1,1]
total = len(x_test)
actualY = tp+fn
actualN = 

7

In [57]:
accuracy = (tp+tn)/total
print(accuracy)

0.5714285714285714


In [58]:
misclassification = 1 - accuracy
print(misclassification)

0.4285714285714286


In [59]:
df

DAY Outlook Temperature Humidity Wind  PlayTennis
0    D1       2           1        0     1         No
1    D2       2           1        0     0         No
2    D3       0           1        0     1        Yes
3    D4       1           2        0     1        Yes
4    D5       1           0        1     1        Yes
5    D6       1           0        1     0         No
6    D7       0           0        1     0        Yes
7    D8       2           2        0     1         No
8    D9       2           0        1     1        Yes
9   D10       1           2        1     1        Yes
10  D11       2           2        1     0        Yes
11  D12       0           2        0     0        Yes
12  D13       0           1        1     1        Yes
13  D14       1           2        0     0         No

In [60]:
x

array([[2, 1, 0, 1],
       [2, 1, 0, 0],
       [0, 1, 0, 1],
       [1, 2, 0, 1],
       [1, 0, 1, 1],
       [1, 0, 1, 0],
       [0, 0, 1, 0],
       [2, 2, 0, 1],
       [2, 0, 1, 1],
       [1, 2, 1, 1],
       [2, 2, 1, 0],
       [0, 2, 0, 0],
       [0, 1, 1, 1],
       [1, 2, 0, 0]], dtype=object)

In [64]:
for i in range(len(x)):
    print(x[:,i].unique())

AttributeError: 'numpy.ndarray' object has no attribute 'unique'

In [91]:
n=[]
df1 = df.iloc[:,1:6]
for i in range(1,len(df.columns)-1):
    t=df.iloc[:,i].unique()
    n.append(len(t)+2)
    
hypo = np.prod(n)
hypo
print(n)

[5, 5, 4, 4]


In [88]:
def pac(hypo,E,D):
    m = (1/E)*(np.log(hypo)+np.log(1/D))
    print(m)
pac(hypo,0.01,0.01)

1059.6634733096075


In [102]:
A = np.array([[7,2,3],[2,3,4],[6,7,8]])


In [99]:
from numpy import linalg
w, v = linalg.eig(A)
print(w)

[ 1.31414284e+01 -1.14142843e+00 -9.89832808e-16]


In [100]:
print(v)

[[ 0.28139173  0.62656506  0.40824829]
 [ 0.3995999   0.36335509 -0.81649658]
 [ 0.87243258 -0.68948481  0.40824829]]


In [103]:
np.cov(A)

array([[ 7., -2., -2.],
       [-2.,  1.,  1.],
       [-2.,  1.,  1.]])

In [164]:
A1=A.mean(axis=1)    
A1

array([4., 3., 7.])

In [128]:
B=np.zeros([3,3])
A[0,0]
for i in range(len(A)):
    for j in range(len(A)):
        B[i,j]=(A[i,j]-A1)
        

In [129]:
B

array([[ 2.33333333, -2.66666667, -1.66666667],
       [-2.66666667, -1.66666667, -0.66666667],
       [ 1.33333333,  2.33333333,  3.33333333]])

In [141]:
x=np.array([11,5,4,9,9,6])
y=np.array([2,14,3,2,1,6])

x1=x.mean()
y1=y.mean()


In [150]:
cov= np.sum((x-x1)*(y-y1))

In [146]:
covx = np.sum((x-x1)**2)

In [147]:
covy = np.sum((y-y1)**2)

In [148]:
covxy = np.zeros([2,2])
covxy

array([[0., 0.],
       [0., 0.]])

In [151]:
covxy[0,0]=covx
covxy[0,1]=cov
covxy[1,0]=cov
covxy[1,1]=covy

In [152]:
covxy

array([[ 37.33333333, -38.33333333],
       [-38.33333333, 119.33333333]])

In [159]:
w,v=linalg.eig(covxy)

In [160]:
w

array([ 22.20451325, 134.46215342])

In [161]:
v

array([[-0.93017808,  0.36710861],
       [-0.36710861, -0.93017808]])