# Data Pre-Processing 


In [26]:
#Importing the libraries
import numpy as np
import matplotlib.pyplot as plt  
import pandas as pd

In [27]:
#importing the data sets
dataset=pd.read_csv('data.csv')
X=dataset.iloc[:,:-1].values  #creating the matrix of all independent values [all rows and columns except last column]
y=dataset.iloc[:,3].values    #create the matrix of dependent values
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [28]:
#Handling missing data
from sklearn.preprocessing import Imputer  #imputer is a class (so caps)
imputer=Imputer(missing_values='NaN',strategy='mean',axis=0)  #fills the missing value with nan and fill the nan with the mean value(mean is default value) of that column
imputer=imputer.fit(X[:,1:3])                                 #fit all rows ,1st and 2nd column
X[:,1:3]=imputer.transform(X[:,1:3])                          #transform(replace) the missing value by mean
X

C:\Users\Pinaka Pani\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [35]:
#Encoding Categorical data
from sklearn.preprocessing import LabelEncoder,OneHotEncoder   #categorical values will be encoded
labelencoder_X=LabelEncoder()  
#encoding the independent Variable
X[:,0]=labelencoder_X.fit_transform(X[:,0])
onehotencoder=OneHotEncoder(categorical_features=[0])
X=onehotencoder.fit_transform(X).toarray()
#encoding the dependent Variable
labelencoder_y=LabelEncoder()
y=labelencoder_y.fit_transform(y)
X


array([[0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        4.40000000e+01, 7.20000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        2.70000000e+01, 4.80000000e+04],
       [1.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
        3.00000000e+01, 5.40000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        3.80000000e+01, 6.10000000e+04],
       [1.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
        4.00000000e+01, 6.37777778e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        3.50000000e+01, 5.80000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        3.87777778e+01, 5.20000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        4.80000000e+01, 7.90000000e+04],
       [1.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
        5.00000000e+01, 

In [33]:
#splitting dataset into test and train
#from sklearn.cross_validation import train_test_split
from sklearn.model_selection import train_test_split
X_train,X_test,y_test,y_train=train_test_split(X,y,test_size=0.2,random_state=0)
#print(X_train)
print(X_test)



[[1.0e+00 0.0e+00 1.0e+00 0.0e+00 3.0e+01 5.4e+04]
 [1.0e+00 0.0e+00 1.0e+00 0.0e+00 5.0e+01 8.3e+04]]


In [37]:
#feature Scaling
from sklearn.preprocessing import StandardScaler
sc_X=StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test=sc_X.transform(X_test)